version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: nodevault-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=nodevault
    networks:
      - nodevault-network

  app:
    build: .
    container_name: nodevault-app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=nodevault
      - COLLECTION_NAME=records
      - NODE_ENV=production
    stdin_open: true
    tty: true
    networks:
      - nodevault-network

volumes:
  mongodb_data:

networks:
  nodevault-network:
    driver: bridge
