version: "3.9"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - nodevault-net
    volumes:
      - mongo-data:/data/db
    # Do not publish ports → keeps MongoDB private

  backend:
    image: itsalihamza133/my-backend-app:latest
    container_name: backend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - nodevault-net
    ports:
      - "3000:3000"  # expose backend port if needed for web interface or testing
    depends_on:
      - mongodb
    tty: true      # allocates terminal
    stdin_open: true  # keeps stdin open for interactive CLI

networks:
  nodevault-net:
    driver: bridge

volumes:
  mongo-data:
